CONTIKI_PROJECT = helloWorld

CFLAGS = -DDATE="\"`date +"%02u %02d %02m %02y %02H %02M %02S"`\""

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
