<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>RLL Protocol Demonstrator</title>

	
	
    <!-- Bootstrap Core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	
    <!-- MetisMenu CSS -->
    <link href="../bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="../dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

     <!-- Custom Fonts -->
    <link href="../bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

     <!-- Own CSS -->
     <!-- 
	 <link href="../bower_components/bootstrap/dist/css/index.css" rel="stylesheet">
	 -->
	  <!-- D3 topology librairy -->
	<script src="libs_add_by_alex/d3/d3.min.js"></script>
	
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="../bower_components/jquery/dist/jquery.min.js"></script>
	<script src="libs_add_by_alex/jquery-ui/jquery-ui.js"></script>
	
<style>
      #received { width: 100%; height: 400px; border: 1px solid #dedede; overflow-y:scroll;}
      #sent { width: 500px; } 
    </style>

	<script type="text/javascript">
				var socket = new WebSocket("ws://192.168.1.1:8081/ws");
var received = $('#received');
console.log(received);
socket.onopen = function(){  
  console.log("connected"); 
}; 
socket.onmessage = function (message) {
  console.log("receiving: " + message.data);
  $('#received').append(message.data);
  $('#received').append($('<br/>'));
$('#received').scrollTop($('#received')[0].scrollHeight);
};

socket.onclose = function(){
  console.log("disconnected"); 
};

var sendMessage = function(message) {
  console.log("sending:" + message.data);
  socket.send(message.data);
};


// GUI Stuff


// send a command to the serial port


$('#clear').click(function(){
  $('#received').empty();
});
		function collectStatistics(){
			window.location.reload(true);
		}
		// send a statistics reset message to the network and reload the page after 10 seconds
		function resetStatistics(){
			socket.send("resetstatistics\n");
			setTimeout(function(){window.location.reload(true);}, 10000);
		}
	</script>

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.phtml">RLL Protocol</a>
            </div>
            <!-- /.navbar-header -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="DEWILOGO">
                               <p align="center"><img src="DEWI-Logo.jpg" align="center" width="200" height="86.9" > </p>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="index.phtml">Home</a>
                        </li>
                        <li>
                            <a href="dataTable.phtml">Table of Nodes</a>
                        </li>
                        <li>
                            <a href="topology.phtml">Light Network Topology</a>
                        </li>
                        <li>
                            <a href="color.phtml">RGB LED Color</a>
                        </li>
			<li>
			    <a href="statistics.phtml">Statistics</a>
			</li>
			<li>
			    <a href="console.html">Console</a>
			</li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Node statistics</h1>
			<?php
				include ("statDBtoJson.php");	
			?>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div  class="row">
		<div class="input-group">
			<span class="input-group-btn">
				<button class="btn btn-warning btn-sm" style="margin-left: 0;" onclick="collectStatistics()">Refresh statistics information</button>&nbsp;
				<button class="btn btn-warning btn-sm" style="margin-left: 0;" onclick="resetStatistics()">Reset statistics</button>
			</span>
                </div>
		<div>
			<p><?php include ("AvgStats.php"); ?></p>
		</div>
		<div>
                   <!-- draw the table on the webpage -->
		    <iframe sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin" src="statstable-JS.html" style="height:700px;width:1000px" scrolling="no"></iframe>
		</div>			
            </div>
<p>Data received from serial port</p>
  <div id="received">
  </div>
  <button id="clear">Clear</button>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
  
</body>
</html>
